name: my_qa
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png
   - assets/images/icon-circle.png
   - assets/images/icon-round.png

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        
  
  
